# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

branches:
  only:
    - master
    - structure_CI

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  - 5.3
  - 5.4
