<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-30 at 10:23:41.
 */

class GalleryContentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var GalleryContent
     */
    protected $object;
    protected $testGalleryName;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	umask(0777);
    	$this->testGalleryName = 'test';
    	$configEnv = new ConfigEnv();   	
    	
    	$this->object = new GalleryContent($this->testGalleryName, TRUE);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    	
    	$configEnv = new ConfigEnv();
    	$gallery_path = $configEnv->getFileUrl() . "/" . $this->testGalleryName;
    	rmdir($gallery_path . '/images');
    	rmdir($gallery_path . '/thumbs');
    	 
    	$this->delDir($gallery_path);
    }

    /**
     * @covers GalleryContent::getNbExistingImages
     */
    public function testGetNbExistingImages()
    {
     	$this->assertEquals(0, $this->object->getNbExistingImages());   
    }

    /**
     * @covers GalleryContent::getGalleryName
     */
    public function testGetGalleryName()
    {
        $this->assertEquals('test', $this->object->getGalleryName());
    }

    /**
     * @covers GalleryContent::getFileImagesDirectory
     * @todo   Implement testGetFileImagesDirectory().
     */
    public function testGetFileImagesDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::getFileThumbsDirectory
     * @todo   Implement testGetFileThumbsDirectory().
     */
    public function testGetFileThumbsDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::getWebImagesDirectory
     * @todo   Implement testGetWebImagesDirectory().
     */
    public function testGetWebImagesDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::getWebThumbsDirectory
     * @todo   Implement testGetWebThumbsDirectory().
     */
    public function testGetWebThumbsDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::getXmlUrl
     * @todo   Implement testGetXmlUrl().
     */
    public function testGetXmlUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::getRoot
     * @todo   Implement testGetRoot().
     */
    public function testGetRoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::getImages
     * @todo   Implement testGetImages().
     */
    public function testGetImages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::addImage
     * @todo   Implement testAddImage().
     */
    public function testAddImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GalleryContent::imagethumb
     * @todo   Implement testImagethumb().
     */
    public function testImagethumb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
    
    private static function delDir($dir) {
    	$files = array_diff(scandir($dir), array('.','..'));
    	foreach ($files as $file) {
    		(is_dir("$dir/$file")) ? rmdir("$dir/$file") : unlink("$dir/$file");
    	}
    	return rmdir($dir);
    }
    
}
